### PR TITLE
ECS - Command Buffers

### PR DESCRIPTION
**Pull request by mathiasmagnusson**
Add a way to buffer some actions to be performed on the `World` at a later stage when possible.

This will make it possible to for example remove certain entities while looping over them.

Todo:
- [x] Command to spawn & despawn entities
- [x] Command to add components to entities
- [x] Add a way to add components to newly spawned entities
- [x] Add a way to get a handle to the new `Entity` being spawned

### CODE REVIEW

**Comment by mathiasmagnusson** [comment]
The current API when creating a `Commands` is not very nice.

**Review by ollisco — APPROVED** [review]
I do not understand it but it looks good

**Review by VincentLagerros — APPROVED** [review]

**Review by TerraDOOM — COMMENTED** [review]
Looks sketchy but it works

**Review by TerraDOOM — APPROVED** [review]
Woops

**Pull request merged**
